const HomeActionTypes = {
  FETCH_HOME_DATA_START: "FETCH_HOME_DATA_START",
  FETCH_HOME_PAGE_BANNER_SUCCESS: "FETCH_HOME_PAGE_BANNER_SUCCESS",
  FETCH_HOME_PAGE_BANNER_FAILURE: "FETCH_HOME_PAGE_BANNER_FAILURE",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",
  TOGGLE_CART: "TOGGLE_CART",
};

export default HomeActionTypes;
