export const HomeActionTypes = {
  FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_BANNERS_START: 'FETCH_BANNERS_START',
  FETCH_BANNERS_SUCCESS: 'FETCH_BANNERS_SUCCESS',
  TRIGGER_NOTIFICATION: 'TRIGGER_NOTIFICATION',
  CLOSE_NOTIFICATION: 'CLOSE_NOTIFICATION',
  SET_LOADING: 'SET_LOADING',
  SET_NOT_LOADING: "SET_NOT_LOADING"
};