export const HomeActionTypes = {
  FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',
  FETCH_BANNERS_START: 'FETCH_BANNERS_START',
  FETCH_BANNERS_SUCCESS: 'FETCH_BANNERS_SUCCESS',
  FETCH_BANNERS_FAILURE: 'FETCH_BANNERS_FAILURE'
};