/* eslint-disable @next/next/link-passhref */
import Head from 'next/head'
import Image from 'next/image'
import Corousel from '../components/Corousel'
import styles from '../styles/Home.module.css'
import category from '../category.json'
import Link from 'next/link'
  import Button from 'react-bootstrap/Button';
import { useState } from 'react'


export default function Home() {
  const [catId, setCatId] = useState('')
  console.log(category)
  return (
    <div className={styles.container}>
      <Head>
        <title>Sabka Bazaar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      
      <main  ><br/>
        <div style={{position:"relative",display:"flex", justifyContent:'center',width:"100%",height:"20%", boxShadow:'-1px 5px 5px -1px rgba(0, 0, 0, 0.3)'}}>
          <Corousel/>
        </div><br/><br/>
        {category.map((ctg,index)=>{
          console.log(ctg.imageUrl)
          if(index%2==0){
            return <>
              <div style={{position:"relative",display:"grid",gridTemplateColumns:"1fr 1fr", width:"100%",height:"20%", boxShadow:'-1px 5px 5px -1px rgba(0, 0, 0, 0.2)'}}>
                <div style={{display:"flex",justifyContent:"center"}}><Image src={`${ctg.imageUrl}`} alt="products" width="400" height="180"/></div>
                  <div style={{display:"",justifyContent:"center", alignItems:"center",textAlign:'center'}}>
                    <h2>{ctg.name}</h2><br/>
                    <h6>{ctg.description}</h6>
                    {/* <Link href="/"><span style={{backgroundColor:"red"}}>Explore More</span></Link> */}
                    <Link href={`products/${ctg.id}`}><Button variant="danger" size="xs">Explore</Button></Link>
                  </div>
              </div><br/><br/>
            </>
          }else{
            return <>
              <div style={{position:"relative",display:"grid",gridTemplateColumns:"1fr 1fr", width:"100%",height:"20%", boxShadow:'-1px 5px 5px -1px rgba(0, 0, 0, 0.2)'}}>
                <div style={{display:"",justifyContent:"center", alignItems:"center",textAlign:'center'}}>
                  <h2>{ctg.name}</h2><br/>
                  <h6>{ctg.description}</h6>
                  <Link href={`products/${ctg.id}`}><Button variant="danger" size="xs">Explore</Button></Link>
                </div>
                <div style={{display:"flex",justifyContent:"center"}}><Image src={`${ctg.imageUrl}`} alt="" width="400" height="180"/></div>
              </div><br/><br/></>
          }
        })}
      </main>
    </div>
  )
}
