export const SET_CATEGORIES="SET_CATEGORIES"
export const GET_CATEGORIES="GET_CATEGORIES"

export const SET_PRODUCTS="SET_PRODUCTS"
export const GET_PRODUCTS="GET_PRODUCTS"

export const TOGGLE_CART="TOGGLE_CART"

export const SET_FILTER="SET_FILTER"

export const SET_BANNER_DATA="SET_BANNER_DATA"
export const GET_BANNER_DATA="GET_BANNER_DATA"