export const CART_ACTION_TYPES = {
    SET_CART_DATA : 'cart/SET_CART_DATA',
    SET_CART_TOGGLE : 'cart/SET_CART_TOGGLE',
    SET_CART_COUNT : 'cart/SET_CART_COUNT',
    SET_CART_TOTAL : 'cart/SET_CART_TOTAL'
}