export const GET_PRODUCTS_LOADING = 'GET_PRODUCTS_LOADING';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = ' GET_PRODUCTS_ERROR';

export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';

export const POST_CART_ITEM_LOADING = 'POST_CART_ITEM_LOADING';
export const POST_CART_ITEM_SUCCESS = 'POST_CART_ITEM_SUCCESS';
export const POST_CART_ITEM_ERROR = ' POST_CART_ITEM_ERROR';
