export const CATEGORIES_ACTION = {
  SET_CATEGORIES_START: "categories/SET_CATEGORIES_START",
  SET_CATEGORIES_SUCCESS: "categories/SET_CATEGORIES_SUCCESS",
  SET_CATEGORIES_FAILED: "categories/SET_CATEGORIES_FAILED",
  SET_ACTIVE_CATEGORY: "categories/SET_ACTIVE_CATEGORY",
};
