export const DEFAULT_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/register'
export const PRODUCT_ROUTE = '/products'
export const SIGNUP = '/signup'
export const HOME= '/Home'
export const CART= '/Cart'
