export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_BANNERS = 'SET_BANNERS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_CART = 'SET_CART';
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
export const SET_CART_STATUS = 'SET_CART_STATUS';
export const SET_REGISTER_STATUS = 'SET_REGISTER_STATUS';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';