const CART_COUNT_INCREMENT = "CART_COUNT_INCREMENT",CART_COUNT_DECREMENT = "CART_COUNT_DECREMENT",
CART_INFO="CART_INFO";
const CART_OPEN = "CART_OPEN",
CART_CLOSE="CART_CLOSE",
SET_USER="SET_USER",
ADD_TO_CART="ADD_TO_CART"
export {
    CART_COUNT_INCREMENT,
    CART_COUNT_DECREMENT,
    CART_INFO,
    CART_OPEN,
    CART_CLOSE,
    SET_USER,
    ADD_TO_CART
}