export const SET_USER_LOGGED_IN_STATUS = 'SET_USER_LOGGED_IN_STATUS';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_RESPONSE = 'LOGIN_USER_RESPONSE';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_RESPONSE = 'REGISTER_USER_RESPONSE';

export const GET_BANNERS_AND_CATEGORIES_REQUEST = 'GET_BANNERS_AND_CATEGORIES_REQUEST';
export const GET_BANNERS_AND_CATEGORIES_RESPONSE = 'GET_BANNERS_AND_CATEGORIES_RESPONSE';