export const SET_USER_LOGGED_IN_STATUS = 'SET_USER_LOGGED_IN_STATUS';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_RESPONSE = 'LOGIN_USER_RESPONSE';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_RESPONSE = 'REGISTER_USER_RESPONSE';

export const GET_BANNERS_AND_CATEGORIES_REQUEST = 'GET_BANNERS_AND_CATEGORIES_REQUEST';
export const GET_BANNERS_AND_CATEGORIES_RESPONSE = 'GET_BANNERS_AND_CATEGORIES_RESPONSE';

export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_RESPONSE = 'GET_PRODUCTS_RESPONSE';

export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';

export const ADD_ITEM_TO_CART_REQUEST = 'ADD_ITEM_TO_CART_REQUEST';
export const ADD_ITEM_TO_CART_RESPONSE = 'ADD_ITEM_TO_CART_RESPONSE';

export const TOGGLE_CART_MODAL_VIEW = 'TOGGLE_CART_MODAL_VIEW';

export const UPDATE_CART_QUANTITY_BY_PRODUCT = 'UPDATE_CART_QUANTITY_BY_PRODUCT';