export const GET_CAROUSEL_DATA = "GET_CAROUSEL_DATA"
export const GET_CAROUSEL_SUCCESS = "GET_CAROUSEL_SUCCESS"
export const GET_CATEGORY_DATA = "GET_CATEGORY_DATA"
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS"
export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_FILTERED_PRODUCT_DATA = "GET_FILTERED_PRODUCT_DATA"
export const GET_CART_DATA_SUCCESS = "GET_CART_DATA_SUCCESS"
export const UPDATE_CART_DATA = "UPDATE_CART_DATA"
























