export const PRODUCTS_ACTION_TYPES = {
  FETCH_PRODUCTS_START: 'category/FETCH_PRODUCTS_START',
  FETCH_PRODUCTS_SUCCESS: 'category/FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILED: 'category/FETCH_PRODUCTS_FAILED',
};
