export const LABEL = {
  SIGNIN: "SignIn",
  SIGNUP: "Signup",
  REGISTER: "Register",
  REGISTER_PRIVACY: "We do not share your personal details with anyone.",
  LOGIN: "Login",
  HOME: "Home",
  EMAIL: "Email",
  PASSWORD: "Password",
  CONFIRM_PASSWORD: "Confirm Password",
  FIRSTNAME: "First Name",
  LASTNAME: "Last Name",
  PRODUCTS: "Products",
  COPYRIGHT: "Copyright © 2011-2018 Sabka Bazaar Grocery Supplies Pvt Ltd",
  LOGOUT: "Logout",
  ITEMS: "items",
  MRP: "MRP Rs.",
  BUY_NOW: "Buy Now",
  NO_CART_ITEMS: "No items in your cart",
  FAV_ITEMS: "Your favourite items are just a click away",
  START_SHOPPING: "Start Shopping",
  RS: "Rs.",
  CHEAPER_MESSAGE: "You won't find it cheaper anywhere.",
  PROMO: "Promo code can be applied on payment page.",
  CHECKOUT: "Proceed to checkout",
  ORDER_PLACE: "Are you sure you want to place order ?",
  CANCEL: "cancel",
  CONFIRM: "confirm",
  MY_CART: "My Cart",
  ORDER_ACCESS: "Get access to your Orders, Wishlist and Recommendations",
};
