export const OPEN_CART_MODAL = 'OPEN_CART_MODAL';
export const CLOSE_CART_MODAL = 'CLOSE_CART_MODAL';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const UPDATE_CART_QUANTITY_AND_TOTAL= 'UPDATE_CART_QUANTITY_AND_TOTAL';
export const CLEAR_CART= 'CLEAR_CART';