const BannersActionTypes = {
  FETCH_BANNERS_START: "FETCH_BANNERS_START",
  FETCH_BANNERS_SUCCESS: "FETCH_BANNERS_SUCCESS",
  FETCH_BANNERS_FAILURE: "FETCH_BANNERS_FAILURE",
};

export default BannersActionTypes;
