export const ProductActions={
    GET_ALL_PRODUCTS:"GET_ALL_PRODUCTS",
    GET_FILTER_BY_PRODUCTS:"GET_FILTER_BY_PRODUCTS",
    REMOVE_STORED_PRODUCTS:'REMOVE_STORED_PRODUCTS',
    GET_PRODUCT_BY_ID:'GET_PRODUCT_BY_ID'
}