export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const ADD_CART_ITEMS = "ADD_CART_ITEMS";
export const ADD_CART_QUANTITY = "ADD_CART_QUANTITY";
export const REDUCE_CART_QUANTITY = "REDUCE_CART_QUANTITY";
export const RESET_CART = "RESET_CART";
