export const CartActionTypes = {
  SHOW_CART: 'SHOW_CART',
  ADD_TO_CART_START: 'ADD_TO_CART_START',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
  INCREMENT_ITEM_QTY: 'INCREMENT_ITEM_QTY',
  DECREMENT_ITEM_QTY: 'DECREMENT_ITEM_QTY'
};