export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CREATE_ADD_TO_CART_SUCCESS = "CREATE_ADD_TO_CART_SUCCESS";
export const CREATE_ADD_TO_CART_FAILURE = "CREATE_ADD_TO_CART_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
