//Error Messages
export const FieldRequired = 'Field cannot be empty.';
export const EmailValid = 'Please enter valid email address.';
export const FirstNameValid = 'Please enter valid first name!';
export const PasswordValid = 'Password must contain atleast 6 characters,1 alphabet and 1 number!';
export const LastNameValid = 'Please enter valid last name!';
export const PasswordUnmatch = "Passwords don't match!";
export const EmailRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;
export const PasswordRegex = '/^(?=.*[A-Za-z])(?=.*d)[A-Za-zd]{6,}$/i';
//Text
export const Copyright = 'Copyright \u00A9 2011-2019 Sabka Bazaar Grocery Supplies Pvt. Ltd';
export const NoAvailableProducts = 'No Product Available';
export const BuyNow = 'Buy Now';
export const MRP = 'MRP';
export const INR = 'Rs.';
export const AllProducts = 'All Products';
export const MyCart = 'My Cart';
export const Item = 'Item';
export const Checkout = 'Proceed to Checkout';
export const SabkaBazarTitle = 'Sabka Bazar';
export const StartShopping = 'Start Shopping';
export const LowestPrice = "You won't find it cheaper anywhere";
export const LowestPriceGuaranteed = 'Lowest Price Guaranteed';
export const CartEmpty = 'No items in your cart!';
export const CartEmptyFavItems = 'Your favourite items are just a click away';
export const PromoCode = 'Promo code can be applied on payment page';
export const RegisterTitle = 'Signup';
export const LoginTitle = 'Login';
export const LoginDescription = 'Get access to your Orders, Wishlist and Recommendations';
export const RegisterDescription = 'We do not share your personal details with anyone.';
export const Email = 'email';
export const Password = 'password';
export const ConfirmPassword = 'confirmPassword';
export const Required = 'required';
