export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const STORE_ALL_PRODUCTS = "STORE_ALL_PRODUCTS";
export const STORE_ALL_CATEGORIES = "STORE_ALL_CATEGORIES";
export const STORE_ALL_BANNER = "STORE_ALL_BANNER";
