const LoginActionTypes = {
  GET_LOGIN_START: "GET_LOGIN_START",
  GET_LOGIN_SUCCESS: "GET_LOGIN_SUCCESS",
  GET_LOGIN_FAILURE: "GET_LOGIN_FAILURE",
  GET_LOGOUT_START: "GET_LOGOUT_START",
  GET_LOGOUT_SUCCESS: "GET_LOGOUT_SUCCESS",
};

export default LoginActionTypes;
