//Action Types
export const FETCH_CATEGORY_START = "FETCH_CATEGORY_START";
export const FETCH_CATEGORY_OK = "FETCH_CATEGORY_OK";
export const FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";
export const SELECT_PRODUCT_CATEGORY = "SELECT_PRODUCT_CATEGORY";
