module.exports = {
    _TITLE: "SABKA BAZAAR",
    _HOME: "Home",
    _SIGNIN: "SignIn",
    _REGISTER: "Register",
    _PRODUCTS: "Products",
    _CART: "Cart",
    _FOOTER_TEXT: "Copyright @2011-2022 Sabka Bazar Grocery Supplies Pvt Ltd",
    _BUY_NOW: "Buy Now",
    _LOWEST_PRICE_MSG: "You won't find it cheaper anywhere.",
    _CHECKOUT_MSG: "Proceed to Checkout",
    _EMPTY_CART_MSG: "You have no items in your shopping cart, start adding some!",
    _PROMO_MSG: "Promo code can be applied on payment page",
    _PRODUCT_ADDED: "Product added to cart successfully",
    _EMPTY_CART_line1: "No items in your cart",
    _EMPTY_CART_line2: "Youy favourite items are just a click away",
    _START_SHOP: "Start Shopping",
    _PAYMENT_SUCCESS: "Your order has been placed. Thank you for shopping with SABKA BAZAAR",
    _LOGIN: "Login",
    _LOGIN_DESC: "Get aacess to your Orders, Wishlists and Recommendations",
    _EMAIL: "Email",
    _PASSWORD: "Password",
    _FIRSTNAME: "First Name",
    _LASTNAME: "Last Name",
    _CONFIRM_PASS: "Confirm Password",
    _REGISTER_DESC: "We do not share your personal details with anyone",
    _SIGN_UP: "Signup",
    _LOGOUT: "Logout",
}