export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const CREATE_ADD_TO_CART_REQUEST = 'CREATE_ADD_TO_CART_REQUEST';
export const CREATE_ADD_TO_CART_SUCCESS = 'CREATE_ADD_TO_CART_SUCCESS';
export const CREATE_ADD_TO_CART_FAILURE = 'CREATE_ADD_TO_CART_FAILURE';

export const PRODUCT_CART_QUANTITY = 'PRODUCT_CART_QUANTITY';
export const MODIFY_PRODUCT_CART_QUANTITY = 'MODIFY_PRODUCT_CART_QUANTITY';
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART';
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART';
