export const FetchActionTypes = {
  FETCH_BANNERS_START: "FETCH_BANNERS_START",
  FETCH_BANNERS_SUCCESS: "FETCH_BANNERS_SUCCESS",
  FETCH_BANNERS_ERROR: "FETCH_BANNERS_ERROR",

  FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_ERROR: "FETCH_CATEGORIES_ERROR",

  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_ERROR: "FETCH_PRODUCTS_ERROR",
};
