export const actions = {
    FETCH_PROD_TYPE: 'FETCH_PROD_TYPE',
    FETCH_ALL_PROD: 'FETCH_ALL_PROD',
    FETCH_BANNERS: 'FETCH_BANNERS',
    UPDATE_CART: 'UPDATE_CART',
    OPEN_CLOSE_CART: 'OPEN_CLOSE_CART'
}