
export const RESET_STORE = 'RESET_STORE';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_BANNERS = 'FETCH_BANNERS';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_CART_OPEN = 'SET_CART_OPEN';
export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';
export const ADD_TO_SHIPPING = 'ADD_TO_SHIPPING';
export const DELETE_FROM_SHIPPING = 'DELETE_FROM_SHIPPING';

