export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
  SET_CART_ITEMS: "SET_CART_ITEMS",
  REMOVE_SELECTED_CART_ITEMS: "REMOVE_SELECTED_CART_ITEMS",
  ADD_SELECTED_CART_ITEMS: "ADD_SELECTED_CART_ITEMS",
  CLEAR_CART_ITEMS: "CLEAR_CART_ITEMS",
};
