export const GET_BANNER_LIST_REQUEST = "GET_BANNER_LIST_REQUEST";
export const GET_BANNER_LIST_SUCCESS = "GET_BANNER_LIST_SUCCESS";
export const GET_BANNER_LIST_FAILED = "GET_BANNER_LIST_FAILED";

export const GET_CATEGORY_LIST_REQUEST = "GET_CATEGORY_LIST_REQUEST";
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS";
export const GET_CATEGORY_LIST_FAILED = "GET_CATEGORY_LIST_FAILED";
