export const GET_BANNER_LIST_FAILED = "GET_BANNER_LIST_FAILED";
export const GET_BANNER_LIST_REQUEST = "GET_BANNER_LIST_REQUEST";
export const GET_BANNER_LIST_SUCCESS = "GET_BANNER_LIST_SUCCESS";

export const GET_CATEGORY_LIST_FAILED = "GET_CATEGORY_LIST_FAILED";
export const GET_CATEGORY_LIST_REQUEST = "GET_CATEGORY_LIST_REQUEST";
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS";

export const GET_PRODUCT_LIST_FAILED = "GET_PRODUCT_LIST_FAILED";
export const GET_PRODUCT_LIST_REQUEST = "GET_PRODUCT_LIST_REQUEST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DECREMENT_PRODUCT_QUANTITY_IN_CART =
  "DECREMENT_PRODUCT_QUANTITY_IN_CART";
export const INCREMENT_PRODUCT_QUANTITY_IN_CART =
  "INCREMENT_PRODUCT_QUANTITY_IN_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const TOGGLE_CART_MODAL = "TOGGLE_CART_MODAL";
