export const actions = {
    FETCH_PRODUCT_TYPE : 'FETCH_PRODUCT_TYPE',
    FETCH_ALL_PRODUCTS: 'FETCH_ALL_PRODUCTS',
    OPEN_CART: 'OPEN_CART',
    UPDATE_TO_CART: 'UPDATE_TO_CART',
    FETCH_CARAUSEL_ITEMS: 'FETCH_CARAUSEL_ITEMS',
}