export const TOGGLE_CART = "TOGGLE_CART";
export const CLOSE_CART = "CLOSE_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_CART_ITEM_QUANTITY = "INCREMENT_CART_ITEM_QUANTITY";
export const DECREMENT_CART_ITEM_QUANTITY = "DECREMENT_CART_ITEM_QUANTITY";
