export const signUpFields = [
    {
        type: 'text',
        name: 'firstName',
        placeHolder: 'First Name',
        label: 'First Name',
        regex: /^[a-zA-Z\-]+$/,
        value:'',
        required: true,
        autoComplete: 'off',
        id: 1,
    },
    {
        type: 'text',
        name: 'lastName',
        placeHolder: 'Last Name',
        label: 'Last Name',
        regex: /^[a-zA-Z\-]+$/,
        value:'',
        required: true,
        autoComplete: 'off',
        id: 2,
    },
    {
        type: 'email',
        name: 'email',
        placeHolder: 'Email',
        label: 'Email',
        regex: /^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/,
        value:'',
        required: true,
        autoComplete: 'on',
        id: 3,
    },
    {
        type: 'password',
        name: 'password',
        placeHolder: 'Password',
        label: 'Password',
        regex: /^(?=.*[0-9])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{6,16}$/,
        value:'',
        required: true,
        autoComplete: 'off',
        id: 4,
    },
    {
        type: 'password',
        name: 'confirmPassword',
        placeHolder: 'Confirm Password',
        label: 'Confirm Password',
        regex: /^(?=.*[0-9])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{6,16}$/,
        value:'',
        required: true,
        autoComplete: 'off',
        id: 5,
    }
]