export const PRODUCT_ACTIONS = {
  FETCH_PRODUCT_START: "product/FETCH_PRODUCT_START",
  FETCH_PRODUCT_SUCCESS: "product/FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAILED: "product/FETCH_PRODUCT_FAILED",
};
