const ProductActionTypes = {
  GET_PRODUCTS_START: "GET_PRODUCTS_START",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
  GET_ADD_TO_CART_START: "GET_ADD_TO_CART_START",
  GET_ADD_TO_CART_SUCCESS: "GET_ADD_TO_CART_SUCCESS",
  GET_ADD_TO_CART_FAILURE: "GET_ADD_TO_CART_FAILURE",
  INCREMENT_QTY_START: "INCREMENT_QTY_START",
  INCREMENT_QTY_SUCCESS: "INCREMENT_QTY_SUCCESS",
  DECREMENT_QTY_START: "DECREMENT_QTY_START",
  DECREMENT_QTY_SUCCESS: "DECREMENT_QTY_SUCCESS",
  REMOVE_CART_ITEM_START: "REMOVE_CART_ITEM_START",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
};

export default ProductActionTypes;
